---
apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-schema
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-upgrade
    spec:
      containers:
        - name: alembic
          image: "192.168.1.18:5000/abyss/db-migrate:latest"
          env:
            - name: DB_CLIENT_STRING
              valueFrom:
                secretKeyRef:
                  name: abyss-bot-token
                  key: DB_CLIENT_STRING
                  optional: false
      restartPolicy: Never
