---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: abyss-prod

resources:
  - ../../base
  - namespace.yaml
  - secret.yaml

configMapGenerator:
  - name: bot-config
    behavior: merge
    files:
      - override.config=bot.config
